theme_color:
  primary: indigo
  accent: blue

notice: 
  - "è¯¥ç«™ç‚¹å°šåœ¨å»ºè®¾ä¸­ã€‚é‡åˆ°é—®é¢˜ï¼Œè¯·<a href='https://github.com/stevezmtstudios/articles/issues/new/choose'>ä¸ååé¦ˆ</a>ï¼"
  - "????!!!!!??!?!?!??!?!?!!!!"
  - "æˆ‘æ˜¯ä¸€ä¸ªæ‡’äººï¼Œæ‰€ä»¥è¿™ä¸ªç«™ç‚¹å¯èƒ½ä¼šå¾ˆä¹…æ‰æ›´æ–°ä¸€æ¬¡ã€‚"
  - "è¿™ä¸ªåšå®¢åŸºæœ¬ä¸Šæ‰€æœ‰çš„ç²¾åŠ›éƒ½èŠ±åœ¨åˆ€æŠŠä¸Šäº†..."
  - "â€œå®‡å®™å°æœºå™¨äººæ˜¯ä»€ä¹ˆç©æ„â€"
  - "// TODO"
  - "æˆ‘å¾ˆå¯çˆ±è¯·<a href='https://space.bilibili.com/474130186'>ç»™æˆ‘é’±</a>qwq"
  - "console.log('Hello World!')"
  - "æˆ˜ç¥èµ·è·³ï¼Œæˆ˜ç¥ç¡è§‰"
  - "å–µï¼"
  - "æ­ªæ¯”å·´åœ"
  - "å†·çŸ¥è¯†â€”â€”â€”é˜¿åšï¼"
  - "ğŸ¥µ...çƒ­çŸ¥è¯†..."
  - "ç¥è¦æ˜¯å…¬ç„¶å»è·Ÿäººä½œå¯¹ï¼Œé‚£æ˜¯ä»»ä½•äººéƒ½éš¾ä»¥å¯¹ä»˜çš„ã€‚ â€”â€”ã€Šè·é©¬å²è¯—ã€‹"
  - "1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536..."
  - "ç«™é•¿é—²ç€æ— èŠæ“äº†ä¸€ä¸ª<a href='/new'>é¡µé¢åˆ›å»ºå™¨</a>ï¼ŒçœŸçš„å¾—å«ä»–æ‰¾ä¸ªç­ä¸Šäº†..."
  - "å…¶å®404é¡µé¢æœ‰ä¸ªåœ°æ–¹èƒ½ç‚¹ï¼Œç”¨é¼ æ ‡æ™ƒæ™ƒå°±èƒ½æ‰¾åˆ°ï¼ˆ"
  - "ä¸è¦è¯•å›¾ä»¥phpä¸ºurlç»“å°¾è®¿é—®æœ¬ç«™ã€‚æœ¬ç«™æ²¡æœ‰ä½¿ç”¨ä»»ä½•phpé¡µé¢ã€‚"
  - "è‡´ä¸€ä½å‹¤åŠ³çš„ä¿„ç½—æ–¯é»‘å®¢ï¼šæœ¬åšå®¢çœŸçš„æ²¡æœ‰ä½¿ç”¨WordPress..."
  - "æœ¬ç«™ç‚¹ä¸æ”¯æŒIEæµè§ˆå™¨ã€‚ï¼ˆçœŸçš„å—ï¼Ÿï¼‰"
  - "::æ³¼å‡ºå»çš„æ°´ï¼Œæˆ‘è¿ç›†éƒ½ä¸è¦ã€‚"
  - "::å¸ˆå‚…ï¼Œæ•™æˆ‘åˆ†èº«æœ¯å§ã€‚â€â€œé¦–å…ˆï¼Œä½ è¦æœ‰æŠŠç”µé”¯ã€‚ã€‚ã€‚â€"
  - "::â€œä½ æ˜¯ä¸€ä¸ªå¾ˆå¥½å¥‡çš„äººâ€â€œä¸ºä»€ä¹ˆè¿™ä¹ˆè¯´ï¼Ÿâ€â€œä½ çœ‹ä½ åˆé—®äº†â€"
  - "::å°æ˜ä¸€å‡ºç”Ÿå°±æ²¡æœ‰æ‰‹ï¼ŒåŸæ¥æ˜¯æ³¨å†Œè´¦å·æ—¶å¿˜è®°é¢†æ–°æ‰‹ç¤¼åŒ…ã€‚"
  - "::äººç±»æ¯å¤©éƒ½ç›–è¢«å­ç¡è§‰ï¼Œæ‰€ä»¥äººç±»æ˜¯è¢«å­æ¤ç‰©ã€‚"
  - "::äººå¾€é«˜å¤„èµ°ï¼Œæ°´å¾€ä½å¤„æµï¼Œäººçš„80%æ˜¯æ°´ï¼Œæ‰€ä»¥å¤§éƒ¨åˆ†äººå°±ç®—åˆ°äº†é«˜å¤„ä¹Ÿè¿˜æ˜¯ä¸‹æµçš„ã€‚"
  - "::å¥¶ç‰›çš„è‹±æ–‡æ˜¯cowï¼Œæ‰€ä»¥ç‰›å¥¶çš„è‹±æ–‡æ˜¯wocã€‚"
  - "::å¤§è‹±åšç‰©é¦†å‘ç”Ÿä¸¥é‡ç›—çªƒæ¡ˆï¼Œè´Ÿè´£äººå‘æ–‡å“­è¯‰åŒè¡Œå†…å·ã€‚"
  - "â€œæˆ‘çš„æ³•åŠ›ä¸æ¯”å¦‚æ¥ä½›å·®ï¼Œä½ æ˜¯æ€ä¹ˆé€ƒå‡ºæˆ‘çš„æ‰‹æŒå¿ƒçš„?â€è€¶ç¨£ä¸è§£åœ°é—®å­™æ‚Ÿç©ºã€‚"
  - "ä½ è¿™è¾ˆå­å°±æ˜¯è¢«å’•å’•åå®³äº†ã€‚"




favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.jpg@128x128.jpg
rss: /atom.xml

email: admin@stevezmt.top
sns:
  twitter:
  facebook:
  google_plus:
  steam: https://steamcommunity.com/id/stevezmt/
  weibo:
  instagram:
  tumblr:
  github: https://github.com/stevezmtstudios/
  linkedin:
  zhihu: https://www.zhihu.com/people/zhang-xian-sheng-70-9
  douban:
  qq: tencent://message/?uin=3579946866&Menu=yes
  wechat:
  bilibili: https://space.bilibili.com/474130186
  custom: https://stevezmt.top/

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: G-T404DHJEEZ
  baidu_site_id:
  cnzz_site_id:

pages:
- name: æ—¶é—´è½´
  link: /timeline
- name: æ ‡ç­¾äº‘
  link: /tagcloud
- name: å‹æƒ…é“¾æ¥
  link: /friends

links:
  - name: å²è’‚å¤«ZMT ä¸»é¡µ
    link: https://stevezmt.top/
  - name: è¿‡æ°”é¡¹ç›®å­˜æ¡£
    link: https://rip.stevezmt.top

    

since: 2024
footer_text: '| <a href="https://icp.gov.moe/?keyword=20240571" target="_blank" class="mdui-text-color-theme-accent">èŒICPå¤‡20240571å·</a>'
license: æ­¤é¡µå†…å®¹éµå¾ª<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"> ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™… (CC BY-NC-SA 4.0) åè®®<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>

gallery:
  fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
  lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: å‘é€åˆ°æ‰‹æœº
  use: plugin
  
donate:
search:
  placeholder: æœç´¢...
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: Ov23li2IcxCrL109at0U
  gitalk_client_secret: 6b1433f474c96a5c5a997a1de53739f6f939470a
  gitalk_repo: articles
  gitalk_owner: stevezmtstudios
  gitalk_sid_type: uuid
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
