theme_color:
  primary: indigo
  accent: blue

notice: "该站点尚在建设中，您可能会遇到各种问题。请<a href='https://github.com/stevezmtstudios/articles/issues/new/choose'>不吝反馈</a>！"


favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.jpg@128x128.jpg
rss: /atom.xml

email: admin@stevezmt.top
sns:
  twitter:
  facebook:
  google_plus:
  steam: https://steamcommunity.com/id/stevezmt/
  weibo:
  instagram:
  tumblr:
  github: https://github.com/stevezmtstudios/
  linkedin:
  zhihu: https://www.zhihu.com/people/zhang-xian-sheng-70-9
  douban:
  qq: tencent://message/?uin=3579946866&Menu=yes
  wechat:
  bilibili: https://space.bilibili.com/474130186
  custom: https://stevezmt.top/

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: G-T404DHJEEZ
  baidu_site_id:
  cnzz_site_id:

pages:
- name: 时间轴
  link: /timeline
- name: 标签云
  link: /tagcloud
- name: 相册
  link: /gallery
- name: 友情链接
  link: /friends

links:
  - name: 史蒂夫ZMT 主页
    link: https://stevezmt.top/
  - name: 过气项目存档
    link: https://rip.stevezmt.top
    
    

since: 2024
footer_text: '| <a href="https://icp.gov.moe/?keyword=20240571" target="_blank" class="mdui-text-color-theme-accent">萌ICP备20240571号</a>'
license: 此页内容遵循<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"> 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>

gallery:
  fancybox_css: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: //cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: //cdn.bootcdn.net/ajax/libs/jquery/3.3.1/jquery.min.js
  lazyload_js: //cdn.bootcdn.net/ajax/libs/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
  
donate:
search:
  placeholder: 搜索...
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: Ov23li2IcxCrL109at0U
  gitalk_client_secret: 6b1433f474c96a5c5a997a1de53739f6f939470a
  gitalk_repo: articles
  gitalk_owner: stevezmtstudios
  gitalk_sid_type: uuid
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
