# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 老史尬侃 - Steve ZMT 's Blog
subtitle: 又名“史蒂夫ZMT”的树洞。
description: 随笔、日志、技术分享、个人作品 Steve ZMT is soliloquize here.
keywords: 
  - blog
  - 博客
  - 随笔
  - SteveZMT 
  - 史蒂夫ZMT
author: Steve ZMT
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.stevezmt.top/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - ".github/**/*" 
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
#syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

## https://developer.mozilla
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: 
  - ".github/**/*"
  - "robots.txt"
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: default

# lazyload image
lazyload:
  enable: true
  onlypost: true # optional
  loadingImg: /images/loading.gif
  isSPA: false # optional
  preloadRatio: 3 # optional, default is 1

excerpt_length: 160
auto_excerpt:
  enable: true
  length: 150

# Markdown
## Docs: https://github.com/niemingzhao/hexo-renderer-markdown#readme
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    langPrefix: language-
    linkify: true
    typographer: true
    quotes: “”‘’
  plugins:
    markdown-it-anchor:
      level: 1
      permalink: true
      slugify: function (s){return encodeURIComponent(String(s).trim().toLowerCase().replace(/\s+/g,"-"))}
      tabIndex: -1
      uniqueSlugStartIndex: 1
      renderPermalink: function (b,c,d,a){var f;var e=[Object.assign(new d.Token("link_open","a",1),{attrs:[["class",c.permalinkClass],["href",c.permalinkHref(b,d)],["aria-hidden",true]]}),new d.Token("link_close","a",-1)];(f=d.tokens[a+1].children)["push"].apply(f,e)}
      permalinkClass: header-anchor
      permalinkSpace: false
      permalinkSymbol: ""
      permalinkBefore: false
    markdown-it-attrs:
      leftDelimiter: "{"
      rightDelimiter: "}"
      allowedAttributes: []
    markdown-it-checkbox:
      divWrap: false
      divClass: checkbox
      idPrefix: checkbox
    markdown-it-texmath:
      katexCssSrc: //cdn.jsdelivr.net/npm/katex/dist/katex.min.css
      texmathCssSrc: //cdn.jsdelivr.net/npm/markdown-it-texmath/css/texmath.min.css
      texmathDelimiters: dollars
      throwOnError: false
      errorColor: "#cc0000"
      macros: { "\\RR": "\\mathbb{R}" }

math:
  enabled: true
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mhchem: true
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# mermaid 
mermaid:
  enable: true 
  version: "8.4.0" 
  startOnload: true  #default true
  theme: 'default'    #default, forest, dark, neutral.


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:SteveZMTstudios/articles.git
    branch: gh-pages
    ignore_hidden: false
    force: true
    include: 
      - ".github/**/*"
